### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by markgoddard**
Ansible lint, syntax check, galaxy import webhook.

### CODE REVIEW

**Review by brtkwr — APPROVED** [review]
Nice, we should add ansible-lint to all the other roles too.

**Comment by markgoddard** [comment]
> Nice, we should add ansible-lint to all the other roles too.

I took this from os-flavors, I think you added it?

**Comment by brtkwr** [comment]
Nope, that was definitely you! https://github.com/stackhpc/ansible-role-os-flavors/blame/master/.travis.yml

**Comment by markgoddard** [comment]
Can't argue with that...

**Pull request merged**
